version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env  # Use environment variables from .env file
      